[package]
name = "mostlywhat-battlestation"
description = "A terminal-styled utility software made in rust-lang"
authors = ["mostlywhat"]
version = "0.0.1"
edition = "2021"

build = "build.rs"

readme = "README.md"
homepage = "https://www.mostlywhat.systems/projects/battlestation"
repository = "https://www.github.com/mostlywhat/battlestation"
license-file = "LICENSE"
keywords = ["terminal", "cli", "rust", "rust-lang", "mostlywhat"]
categories = ["command-line-utilities"]

[dependencies]
crossterm = "0.27.0"
ratatui = { version = "0.26.2", features = ["all-widgets"] }



[build-dependencies]
winres = "0.1.12"
