name: Compile Binaries for Release
on: [push]

env:
  PKG_NAME: "MostlyWhat's Battlestation-development"
  PKG_VERSION: "0.0.1"

jobs:
  Windows:
    name: Compile Windows Binaries
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: actions/checkout
        uses: actions/checkout@v2

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      #Publishing to Release
      - name: Release to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          name: Battlestation Version ${{ env.env.PKG_VERSION }}
          tag_name: v${{ env.PKG_VERSION }}
          body: "Automated Battlestation Build Version ${{ env.PKG_VERSION }}"
          files: ${{ github.workspace }}\battlestation\target\release\${{ PKG_NAME }}.exe

  MacOS:
    name: Compile MacOS Binaries
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: actions/checkout
        uses: actions/checkout@v2

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      #Publishing to Release
      - name: Release to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          name: Battlestation Version ${{ env.PKG_VERSION }}
          tag_name: v${{ env.PKG_VERSION }}
          body: "Automated Battlestation Build Version ${{ env.PKG_VERSION }}"
          files: ${{ github.workspace }}\battlestation\target\release\${{ PKG_NAME }}.app

  Linux:
    name: Compile Linux Binaries
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: actions/checkout
        uses: actions/checkout@v2

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      #Publishing to Release
      - name: Release to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          name: Battlestation Version ${{ env.PKG_VERSION }}
          tag_name: v${{ env.PKG_VERSION }}
          body: "Automated Battlestation Build Version ${{ env.PKG_VERSION }}"
          files: ${{ github.workspace }}\battlestation\target\release\${{ PKG_NAME }}
